### ISSUE TITLE
batch-size error

### ISSUE THREAD

**Issue by k1anshul** [sail-sg/volo#24]
![image](https://user-images.githubusercontent.com/60307418/124865018-89ee7180-dfd7-11eb-834f-9ee8780bf534.png)

getting this error of 
Training with a single process on 1 GPUs.
WARNING: Neither APEX or native Torch AMP is available, using float32. Install NVIDA apex or upgrade to PyTorch 1.6
Model volo_d1 created, param count: 25865120
Data processing configuration for current model + dataset:
	input_size: (3, 224, 224)
	interpolation: bicubic
	mean: (0.485, 0.456, 0.406)
	std: (0.229, 0.224, 0.225)
	crop_pct: 0.96
AMP not enabled. Training in float32.
Scheduled epochs: 15
Traceback (most recent call last):
  File "main.py", line 948, in <module>
    main()
  File "main.py", line 502, in main
    batch_size=args.batch_size)
  File "/usr/local/lib/python3.7/dist-packages/timm/data/dataset_factory.py", line 29, in create_dataset
    ds = ImageDataset(root, parser=name, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/timm/data/dataset.py", line 31, in __init__
    parser = create_parser(parser or '', root=root, class_map=class_map)
  File "/usr/local/lib/python3.7/dist-packages/timm/data/parsers/parser_factory.py", line 22, in create_parser
    assert os.path.exists(root)
AssertionError

**Comment by k1anshul** [comment]
Even when i put --batch-size it stii give same erroe
